const flagArray = [
  {
    name: "Roman Empire",
    colors: ["Red", "Puple", "Gold"],
    design: ["animal", "text"],
    image: require("./images/RomanEmpire1.png"),
    link: "https://en.wikipedia.org/wiki/Roman_Empire",
    id: 1,
  },
  {
    name: "Sparta",
    colors: ["Red", "Yellow", "Black"],
    design: ["Symbol", "Text"],
    image: require("./images/Sparta1.png"),
    link: "https://en.wikipedia.org/wiki/Sparta",
    id: 2,
  },
  {
    name: "Qing Dynasty",
    colors: ["Yellow", "Blue", "Red"],
    design: ["Animal"],
    image: require("./images/Qing.png"),
    link: "https://en.wikipedia.org/wiki/Qing_dynasty",
    id: 3,
  },
  {
    name: "Aceh Sultanate",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Aceh.png"),
    link: "https://en.wikipedia.org/wiki/Aceh_Sultanate",
    id: 4,
  },
  {
    name: "Korean Empire",
    colors: ["White", "Red", "Blue"],
    design: ["Symbol"],
    image: require("./images/Korea.png"),
    link: "https://en.wikipedia.org/wiki/Korean_Empire",
    id: 5,
  },
  {
    name: "Byzantine Empire",
    colors: ["Red", "Yellow"],
    design: ["Stripes", "Text"],
    image: require("./images/Byzantine.png"),
    link: "https://en.wikipedia.org/wiki/Byzantine_Empire",
    id: 6,
  },
  {
    name: "Republic of Corsica",
    colors: ["White", "Black"],
    design: ["Symbol", "Animal"],
    image: require("./images/Corsica.png"),
    link: "https://en.wikipedia.org/wiki/Corsican_Republic",
    id: 7,
  },
  {
    name: "East Germany",
    colors: ["Black", "Red", "Yellow"],
    design: ["Stripes", "Symbol"],
    image: require("./images/East_Germany.png"),
    link: "https://en.wikipedia.org/wiki/East_Germany",
    id: 8,
  },
  {
    name: "Republic of Ragusa",
    colors: ["White", "Red", "Yellow", "Blue"],
    design: ["Text", "Animal"],
    image: require("./images/Ragusa.png"),
    link: "https://en.wikipedia.org/wiki/Republic_of_Ragusa",
    id: 9,
  },
  {
    name: "Free City of Hamburg",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Hamburg.png"),
    link: "https://en.wikipedia.org/wiki/Hamburg#Medieval_Hamburg",
    id: 10,
  },
  {
    name: "Emirate of Granada",
    colors: ["Red", "Yellow"],
    design: ["Text"],
    image: require("./images/Granada.png"),
    link: "https://en.wikipedia.org/wiki/Emirate_of_Granada",
    id: 11,
  },
  {
    name: "Federal Republic of Central America",
    colors: ["Blue", "White"],
    design: ["Stripes", "Symbol", "Text"],
    image: require("./images/Central_America.png"),
    link: "https://en.wikipedia.org/wiki/Federal_Republic_of_Central_America",
    id: 12,
  },
  {
    name: "Republic of Independant Guiana",
    colors: ["Black", "White", "Red"],
    design: ["Symbol", "Stripes"],
    image: require("./images/Guiana.png"),
    link: "https://en.wikipedia.org/wiki/Republic_of_Independent_Guiana",
    id: 13,
  },
  {
    name: "Anjouan",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Anjouan.png"),
    link: "https://en.wikipedia.org/wiki/Anjouan",
    id: 14,
  },
  {
    name: "Ashanti Empire",
    colors: ["Yellow", "Black", "White", "Green"],
    design: ["Symbol"],
    image: require("./images/Ashanti.png"),
    link: "https://en.wikipedia.org/wiki/Ashanti_Empire",
    id: 15,
  },
  {
    name: "Biafra",
    colors: ["Red", "Black", "Green", "Yellow"],
    design: ["Symbol"],
    image: require("./images/Biafra.png"),
    link: "https://en.wikipedia.org/wiki/Biafra",
    id: 16,
  },
  {
    name: "Katanga",
    colors: ["Red", "Green", "White"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Katanga.png"),
    link: "https://en.wikipedia.org/wiki/State_of_Katanga",
    id: 17,
  },
  {
    name: "Kingdom of Imerina",
    colors: ["Red", "White"],
    design: ["Stripes"],
    image: require("./images/Merina.png"),
    link: "https://en.wikipedia.org/wiki/Merina_Kingdom",
    id: 18,
  },
  {
    name: "Independant Moheli",
    colors: ["Red", "Yellow"],
    design: ["Stripes"],
    image: require("./images/Moheli.png"),
    link: "https://en.wikipedia.org/wiki/Moh%C3%A9li",
    id: 19,
  },
  {
    name: "Natalia Republic",
    colors: ["Red", "White", "Blue"],
    design: ["Stripes"],
    image: require("./images/Natalia.png"),
    link: "https://en.wikipedia.org/wiki/Natalia_Republic",
    id: 20,
  },
];

export default flagArray;
