const flagArray = [
  {
    name: "Roman Empire",
    colors: ["Red", "Purple", "Gold"],
    design: ["animal", "text"],
    image: require("./images/RomanEmpire1.png"),
    link: "https://en.wikipedia.org/wiki/Roman_Empire",
    id: 1,
  },
  {
    name: "Sparta",
    colors: ["Red", "Yellow", "Black"],
    design: ["Symbol", "Text"],
    image: require("./images/Sparta1.png"),
    link: "https://en.wikipedia.org/wiki/Sparta",
    id: 2,
  },
  {
    name: "Qing Dynasty",
    colors: ["Yellow", "Blue", "Red"],
    design: ["Animal"],
    image: require("./images/Qing.png"),
    link: "https://en.wikipedia.org/wiki/Qing_dynasty",
    id: 3,
  },
  {
    name: "Aceh Sultanate",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Aceh.png"),
    link: "https://en.wikipedia.org/wiki/Aceh_Sultanate",
    id: 4,
  },
  {
    name: "Korean Empire",
    colors: ["White", "Red", "Blue"],
    design: ["Symbol"],
    image: require("./images/Korea.png"),
    link: "https://en.wikipedia.org/wiki/Korean_Empire",
    id: 5,
  },
  {
    name: "Byzantine Empire",
    colors: ["Red", "Yellow"],
    design: ["Stripes", "Text"],
    image: require("./images/Byzantine.png"),
    link: "https://en.wikipedia.org/wiki/Byzantine_Empire",
    id: 6,
  },
  {
    name: "Republic of Corsica",
    colors: ["White", "Black"],
    design: ["Symbol", "Animal"],
    image: require("./images/Corsica.png"),
    link: "https://en.wikipedia.org/wiki/Corsican_Republic",
    id: 7,
  },
  {
    name: "East Germany",
    colors: ["Black", "Red", "Yellow"],
    design: ["Stripes", "Symbol"],
    image: require("./images/East_Germany.png"),
    link: "https://en.wikipedia.org/wiki/East_Germany",
    id: 8,
  },
  {
    name: "Republic of Ragusa",
    colors: ["White", "Red", "Yellow", "Blue"],
    design: ["Text", "Animal"],
    image: require("./images/Ragusa.png"),
    link: "https://en.wikipedia.org/wiki/Republic_of_Ragusa",
    id: 9,
  },
  {
    name: "Free City of Hamburg",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Hamburg.png"),
    link: "https://en.wikipedia.org/wiki/Hamburg#Medieval_Hamburg",
    id: 10,
  },
  {
    name: "Emirate of Granada",
    colors: ["Red", "Yellow"],
    design: ["Text"],
    image: require("./images/Granada.png"),
    link: "https://en.wikipedia.org/wiki/Emirate_of_Granada",
    id: 11,
  },
  {
    name: "Federal Republic of Central America",
    colors: ["Blue", "White"],
    design: ["Stripes", "Symbol", "Text"],
    image: require("./images/Central_America.png"),
    link: "https://en.wikipedia.org/wiki/Federal_Republic_of_Central_America",
    id: 12,
  },
  {
    name: "Republic of Independant Guiana",
    colors: ["Black", "White", "Red"],
    design: ["Symbol", "Stripes"],
    image: require("./images/Guiana.png"),
    link: "https://en.wikipedia.org/wiki/Republic_of_Independent_Guiana",
    id: 13,
  },
  {
    name: "Anjouan",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Anjouan.png"),
    link: "https://en.wikipedia.org/wiki/Anjouan",
    id: 14,
  },
  {
    name: "Ashanti Empire",
    colors: ["Yellow", "Black", "White", "Green"],
    design: ["Symbol"],
    image: require("./images/Ashanti.png"),
    link: "https://en.wikipedia.org/wiki/Ashanti_Empire",
    id: 15,
  },
  {
    name: "Biafra",
    colors: ["Red", "Black", "Green", "Yellow"],
    design: ["Symbol"],
    image: require("./images/Biafra.png"),
    link: "https://en.wikipedia.org/wiki/Biafra",
    id: 16,
  },
  {
    name: "Katanga",
    colors: ["Red", "Green", "White"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Katanga.png"),
    link: "https://en.wikipedia.org/wiki/State_of_Katanga",
    id: 17,
  },
  {
    name: "Kingdom of Imerina",
    colors: ["Red", "White"],
    design: ["Stripes"],
    image: require("./images/Merina.png"),
    link: "https://en.wikipedia.org/wiki/Merina_Kingdom",
    id: 18,
  },
  {
    name: "Independant Moheli",
    colors: ["Red", "Yellow"],
    design: ["Stripes"],
    image: require("./images/Moheli.png"),
    link: "https://en.wikipedia.org/wiki/Moh%C3%A9li",
    id: 19,
  },
  {
    name: "Natalia Republic",
    colors: ["Red", "White", "Blue"],
    design: ["Stripes"],
    image: require("./images/Natalia.png"),
    link: "https://en.wikipedia.org/wiki/Natalia_Republic",
    id: 20,
  },
  {
    name: "Orange Free State",
    colors: ["Orange", "White", "Red", "Blue"],
    design: ["Stripes"],
    image: require("./images/Orange.png"),
    link: "https://en.wikipedia.org/wiki/Orange_Free_State",
    id: 21,
  },
  {
    name: "Islands of Refreshment",
    colors: ["Red", "White", "Blue"],
    design: ["Stripes"],
    image: require("./images/Refreshment.png"),
    link: "https://en.wikipedia.org/wiki/Islands_of_Refreshment",
    id: 22,
  },
  {
    name: "Rhodesia",
    colors: ["Red", "White", "Green", "Yellow"],
    design: ["Symbol", "Animal", "Text", "Stripes"],
    image: require("./images/Rhodesia.png"),
    link: "https://en.wikipedia.org/wiki/Rhodesia",
    id: 23,
  },
  {
    name: "Republic of the Rif",
    colors: ["Red", "White", "Green"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Rif.png"),
    link: "https://en.wikipedia.org/wiki/Republic_of_the_Rif",
    id: 24,
  },
  {
    name: "South Kasai",
    colors: ["Red", "Green", "Yellow"],
    design: ["Stripes", "Text"],
    image: require("./images/South_Kasai.png"),
    link: "https://en.wikipedia.org/wiki/South_Kasai",
    id: 25,
  },
  {
    name: "Tanganyika",
    colors: ["Green", "Black", "Yellow"],
    design: ["Stripes"],
    image: require("./images/Tanganiyka.png"),
    link: "https://en.wikipedia.org/wiki/Tanganyika_(1961%E2%80%931964)",
    id: 26,
  },
  {
    name: "Sultanate of Zanzibar",
    colors: ["Red", "Green", "Yellow"],
    design: ["Symbol"],
    image: require("./images/Zanzibar.png"),
    link: "https://en.wikipedia.org/wiki/Sultanate_of_Zanzibar",
    id: 27,
  },
  {
    name: "Union of South Africa",
    colors: ["Orange", "White", "Blue"],
    design: ["Stripes"],
    image: require("./images/South_Africa.png"),
    link: "https://en.wikipedia.org/wiki/Union_of_South_Africa",
    id: 28,
  },
  {
    name: "Kingdom of Kongo",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Kongo.png"),
    link: "https://en.wikipedia.org/wiki/Kingdom_of_Kongo",
    id: 29,
  },
  {
    name: "Mali Empire",
    colors: ["Red", "Yellow"],
    design: ["Stripes"],
    image: require("./images/Mali.png"),
    link: "https://en.wikipedia.org/wiki/Mali_Empire",
    id: 30,
  },
  {
    name: "Banten Sultanate",
    colors: ["Yellow", "White"],
    design: ["Symbol"],
    image: require("./images/Banten.png"),
    link: "https://en.wikipedia.org/wiki/Banten_Sultanate",
    id: 31,
  },
  {
    name: "Negros Republic",
    colors: ["Red", "White", "Blue", "Yellow"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Negros.png"),
    link: "https://en.wikipedia.org/wiki/Negros#Negros_Revolution_and_formation_of_Republic_of_Negros",
    id: 32,
  },
  {
    name: "Sultanate of Maguindanao",
    colors: ["Yellow"],
    design: ["Stripes"],
    image: require("./images/Maguindanao.png"),
    link: "https://en.wikipedia.org/wiki/Sultanate_of_Maguindanao",
    id: 33,
  },
  {
    name: "Republic of Vietnam",
    colors: ["Yellow", "Red"],
    design: ["Stripes"],
    image: require("./images/Vietnam.png"),
    link: "https://en.wikipedia.org/wiki/South_Vietnam",
    id: 34,
  },
  {
    name: "Sultanate of Mataram",
    colors: ["Red", "White", "Blue"],
    design: ["Symbol"],
    image: require("./images/Mataram.png"),
    link: "https://en.wikipedia.org/wiki/Mataram_Sultanate",
    id: 35,
  },
  {
    name: "Maratha Empire",
    colors: ["Orange", "White"],
    design: ["Stripes"],
    image: require("./images/Maratha.png"),
    link: "https://en.wikipedia.org/wiki/Maratha_Empire",
    id: 36,
  },
  {
    name: "Mughal Empire",
    colors: ["Green", "Yellow"],
    design: ["Animal", "Symbol"],
    image: require("./images/Mughal.png"),
    link: "https://en.wikipedia.org/wiki/Mughal_Empire",
    id: 37,
  },
  {
    name: "Kingdom of Sikkim",
    colors: ["Red", "White", "Yellow"],
    design: ["Symbol"],
    image: require("./images/Sikkim.png"),
    link: "https://en.wikipedia.org/wiki/Kingdom_of_Sikkim",
    id: 38,
  },
  {
    name: "South Yemen",
    colors: ["Black", "Red", "White"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Yemen.png"),
    link: "https://en.wikipedia.org/wiki/South_Yemen",
    id: 39,
  },
  {
    name: "Sultanate of Sulu",
    colors: ["Purple", "White"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Sulu.png"),
    link: "https://en.wikipedia.org/wiki/Sultanate_of_Sulu",
    id: 40,
  },
  {
    name: "Tagalog Republic",
    colors: ["Red", "White"],
    design: ["Symbol"],
    image: require("./images/Tagalog.png"),
    link: "https://en.wikipedia.org/wiki/Tagalog_Republic",
    id: 41,
  },
  {
    name: "Tibetan Empire",
    colors: ["Red", "Blue", "White", "Green", "Yellow"],
    design: ["Stripes", "Animal", "Symbol"],
    image: require("./images/Tibet.png"),
    link: "https://en.wikipedia.org/wiki/Tibetan_Empire",
    id: 42,
  },
  {
    name: "Tondo",
    colors: ["Red", "White"],
    design: ["Stripes"],
    image: require("./images/Tondo.png"),
    link: "https://en.wikipedia.org/wiki/Tondo_(historical_polity)",
    id: 43,
  },
  {
    name: "East Turkestan",
    colors: ["Blue", "White"],
    design: ["Symbol"],
    image: require("./images/Turkestan.png"),
    link: "https://en.wikipedia.org/wiki/East_Turkestan",
    id: 44,
  },
  {
    name: "Kingdom of Tahiti",
    colors: ["Red", "White"],
    design: ["Stripes"],
    image: require("./images/Tahiti.png"),
    link: "https://en.wikipedia.org/wiki/Tahiti",
    id: 45,
  },
  {
    name: "Kingdom of Raiatea",
    colors: ["Red", "White"],
    design: ["Stripes"],
    image: require("./images/Raiatea.png"),
    link: "https://en.wikipedia.org/wiki/List_of_monarchs_of_Raiatea",
    id: 46,
  },
  {
    name: "Kingdom of Bora Bora",
    colors: ["White", "Red"],
    design: ["Symbol"],
    image: require("./images/Bora_Bora.png"),
    link: "https://en.wikipedia.org/wiki/Kingdom_of_Bora_Bora",
    id: 47,
  },
  {
    name: "Kingdom of Huahine",
    colors: ["Red", "White"],
    design: ["Stripes"],
    image: require("./images/Huahine.png"),
    link: "https://en.wikipedia.org/wiki/Huahine",
    id: 48,
  },
  {
    name: "Kingdom of Mangareva",
    colors: ["Blue", "White"],
    design: ["Stripes", "Symbol"],
    image: require("./images/Mangareva.png"),
    link: "https://en.wikipedia.org/wiki/Mangareva",
    id: 49,
  },
  {
    name: "Kingdom of Rurutu",
    colors: ["Red", "Blue", "White"],
    design: ["Stripes", "Text"],
    image: require("./images/Rurutu.png"),
    link: "https://en.wikipedia.org/wiki/Rurutu",
    id: 50,
  },
];

export default flagArray;
